# Generated by Django 4.1.6 on 2023-02-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantiy'),
            preserve_default=False,
        ),
    ]
