# Generated by Django 4.1.6 on 2023-02-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_foodmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='phone',
            field=models.IntegerField(max_length=100, verbose_name='phone'),
        ),
    ]
